import type { Job, User } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Budi Santoso',
    email: 'budi.santoso@example.com',
    role: 'seeker',
    avatarUrl: 'https://picsum.photos/seed/user1/100/100',
    skills: ['Barista', 'Pelayan', 'Kasir'],
  },
  {
    id: 'user-2',
    name: 'Siti Aminah',
    email: 'siti.aminah@example.com',
    role: 'seeker',
    avatarUrl: 'https://picsum.photos/seed/user2/100/100',
    skills: ['Staff Gudang', 'Kurir', 'Administrasi'],
  },
  {
    id: 'user-3',
    name: 'Agus Wijaya',
    email: 'agus.wijaya@example.com',
    role: 'seeker',
    avatarUrl: 'https://picsum.photos/seed/user3/100/100',
    skills: ['Dapur', 'Kebersihan', 'Pengemudi'],
  },
    {
    id: 'user-4',
    name: 'Dewi Lestari',
    email: 'dewi.lestari@example.com',
    role: 'seeker',
    avatarUrl: 'https://picsum.photos/seed/user4/100/100',
    skills: ['Kasir', 'Administrasi', 'Pelayan'],
  },
  {
    id: 'user-5',
    name: 'Eko Prasetyo',
    email: 'eko.prasetyo@example.com',
    role: 'seeker',
    avatarUrl: 'https://picsum.photos/seed/user5/100/100',
    skills: ['Kurir', 'Pengemudi', 'Staff Gudang'],
  },
  {
    id: 'emp-1',
    name: 'Kopi Kenangan',
    email: 'hr@kopikenangan.com',
    role: 'employer',
    avatarUrl: 'https://picsum.photos/seed/emp1/100/100',
    skills: [],
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Barista Full-Time',
    description: 'Mencari barista berpengalaman untuk kedai kopi kami yang sedang berkembang.',
    salary: 4500000,
    type: 'Bulanan',
    location: 'Jakarta Selatan',
    status: 'Aktif',
    skills: ['Barista', 'Kasir'],
    company: {
      id: 'comp-1',
      name: 'Kopi Enak Jaya',
      logoUrl: 'https://picsum.photos/seed/logo1/100/100',
    },
  },
  {
    id: 'job-2',
    title: 'Pelayan Restoran (Harian)',
    description: 'Dibutuhkan pelayan untuk acara akhir pekan. Pengalaman tidak diutamakan.',
    salary: 150000,
    type: 'Harian',
    location: 'Bandung',
    status: 'Aktif',
    skills: ['Pelayan'],
    company: {
      id: 'comp-2',
      name: 'Restoran Sederhana',
      logoUrl: 'https://picsum.photos/seed/logo2/100/100',
    },
  },
  {
    id: 'job-3',
    title: 'Staff Gudang (Mingguan)',
    description: 'Membantu proses packing dan unpacking barang di gudang. Dibutuhkan fisik yang kuat.',
    salary: 1200000,
    type: 'Mingguan',
    location: 'Surabaya',
    status: 'Ditutup',
    skills: ['Staff Gudang'],
    company: {
      id: 'comp-3',
      name: 'Logistik Cepat',
      logoUrl: 'https://picsum.photos/seed/logo3/100/100',
    },
  },
  {
    id: 'job-4',
    title: 'Kasir Toko Retail',
    description: 'Melayani pembayaran pelanggan dengan ramah dan akurat.',
    salary: 3800000,
    type: 'Bulanan',
    location: 'Jakarta Pusat',
    status: 'Aktif',
    skills: ['Kasir'],
    company: {
      id: 'comp-1',
      name: 'Kopi Enak Jaya',
      logoUrl: 'https://picsum.photos/seed/logo1/100/100',
    },
  },
    {
    id: 'job-5',
    title: 'Kurir Paket Area Jakarta Barat',
    description: 'Mengantarkan paket ke pelanggan di area Jakarta Barat. Memiliki SIM C dan motor pribadi.',
    salary: 250000,
    type: 'Harian',
    location: 'Jakarta Barat',
    status: 'Aktif',
    skills: ['Kurir', 'Pengemudi'],
    company: {
      id: 'comp-3',
      name: 'Logistik Cepat',
      logoUrl: 'https://picsum.photos/seed/logo3/100/100',
    },
  },
   {
    id: 'job-6',
    title: 'Kitchen Crew',
    description: 'Membantu persiapan bahan makanan dan menjaga kebersihan dapur.',
    salary: 180000,
    type: 'Harian',
    location: 'Tangerang',
    status: 'Aktif',
    skills: ['Dapur', 'Kebersihan'],
    company: {
      id: 'comp-2',
      name: 'Restoran Sederhana',
      logoUrl: 'https://picsum.photos/seed/logo2/100/100',
    },
  }
];
